name = "medium"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNWY1NWFmZjQtMDRkNy00YWZjLWE1OGItMDI3YmYwMjc2NjdmIiwidGVuYW50X2lkIjoiYjJhYjA4ZWIyMTRhZTMzZDFlNTVkOTg4MDE4MDA3Zjk3MWVhYWFmOTRlNGIwNjBkYzNhM2EwN2MyODFkYWVkYSIsImludGVybmFsX3NlY3JldCI6IjBiZTcxMTBmLTQwYzMtNGViYi04OTkzLTgxZmNmZGFhMzc0YiJ9.QlCUHBHUFoRnIh2Hyi86WvGhElAliRPAQbsdl9GIIbg"
JWT_SECRET = "pavani09"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
